\ox\bin\oxl tst_alternative_formulas.ox	   > tst.out
\ox\bin\oxl tst_approximate.ox			   >> tst.out
\ox\bin\oxl tst_binomial.ox				   >> tst.out
\ox\bin\oxl tst_black_scholes.ox		   >> tst.out
\ox\bin\oxl tst_bondopt_black_scholes.ox   >> tst.out
\ox\bin\oxl tst_bondopt_rend_bart.ox	   >> tst.out
\ox\bin\oxl tst_bondopt_vasicek.ox		   >> tst.out
\ox\bin\oxl tst_bonds.ox				   >> tst.out
\ox\bin\oxl tst_cash_flow.ox			   >> tst.out
\ox\bin\oxl tst_currency.ox				   >> tst.out
\ox\bin\oxl tst_exotics.ox				   >> tst.out
\ox\bin\oxl tst_finite_diff.ox			   >> tst.out
\ox\bin\oxl tst_futures.ox				   >> tst.out
\ox\bin\oxl tst_mv_calc_port.ox			   >> tst.out
\ox\bin\oxl tst_simulate.ox				   >> tst.out
\ox\bin\oxl tst_simulate_general.ox		   >> tst.out
\ox\bin\oxl tst_term_structure.ox		   >> tst.out
