decl cflow_amounts, cflow_times;
setflow(inflow,times);  
cash_flow_pv(r); 
cash_flow_pv_discrete(r);  
cash_flow_irr(); 
single_irr(); 
multiple_roots(); 
modified_irr(financerate, reinvestmentrate); 
count_sign_changes(v); 	
cash_flow_unique_irr();
breakeven(); 
print_summary(finrate, investrate);
